При обработке исключений можно точно задать поведение программы.
В данном примере catch ловим "особый случай", который можем получить при try (исключение типа ArithmeticException), и обрабатываем его.
В finally стандартное завершение.


